--
-- PostgreSQL database dump
--

\restrict OYS4w40wF3sIlAzHPQfBqI4dEATdzQSSdpV7KEcgYzWKRW5o7X1t5HxeJa39xPp

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

-- Started on 2026-04-22 16:06:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16422)
-- Name: ms_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_categories (
                                      id integer CONSTRAINT ms_categories_category_id_not_null NOT NULL,
                                      user_id integer NOT NULL,
                                      category_name text NOT NULL,
                                      created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.ms_categories OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16439)
-- Name: ms_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16405)
-- Name: ms_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_users (
                                 id integer NOT NULL,
                                 username text CONSTRAINT ms_users_user_id_not_null NOT NULL,
                                 emails text NOT NULL,
                                 first_name text,
                                 last_name text,
                                 phone_number text,
                                 password_hash text DEFAULT 'dev'::text,
                                 created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 updated_at timestamp without time zone
);


ALTER TABLE public.ms_users OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16417)
-- Name: ms_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4822 (class 2606 OID 16433)
-- Name: ms_categories ms_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_categories
    ADD CONSTRAINT ms_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4818 (class 2606 OID 16419)
-- Name: ms_users ms_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_users
    ADD CONSTRAINT ms_users_pkey PRIMARY KEY (id);


--
-- TOC entry 4820 (class 2606 OID 16421)
-- Name: ms_users ms_users_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_users
    ADD CONSTRAINT ms_users_user_id_key UNIQUE (username);


--
-- TOC entry 4823 (class 2606 OID 16434)
-- Name: ms_categories ms_categories_users_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_categories
    ADD CONSTRAINT ms_categories_users_fkey FOREIGN KEY (user_id) REFERENCES public.ms_users(id) ON UPDATE CASCADE ON DELETE CASCADE;


-- Completed on 2026-04-22 16:06:55

--
-- PostgreSQL database dump complete
--

\unrestrict OYS4w40wF3sIlAzHPQfBqI4dEATdzQSSdpV7KEcgYzWKRW5o7X1t5HxeJa39xPp

