--
-- PostgreSQL database dump
--

\restrict 7dfoNOZq59VJPcxAmaTq89l5GUvSkRMkrUCb8CsxdqMuYcXTzaLWYVkhajNKPAK

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

-- Started on 2026-06-17 15:20:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 16455)
-- Name: ms_budgets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_budgets (
                                   id integer NOT NULL,
                                   user_id integer NOT NULL,
                                   name text NOT NULL
);


ALTER TABLE public.ms_budgets OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16513)
-- Name: ms_budgets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_budgets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_budgets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16422)
-- Name: ms_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_categories (
                                      id integer CONSTRAINT ms_categories_category_id_not_null NOT NULL,
                                      user_id integer NOT NULL,
                                      name text CONSTRAINT ms_categories_category_name_not_null NOT NULL
);


ALTER TABLE public.ms_categories OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16439)
-- Name: ms_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16470)
-- Name: ms_months; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_months (
                                  id integer NOT NULL,
                                  budget_id integer NOT NULL,
                                  year integer NOT NULL,
                                  month integer NOT NULL
);


ALTER TABLE public.ms_months OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16512)
-- Name: ms_months_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_months ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_months_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16440)
-- Name: ms_subcategories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_subcategories (
                                         id integer NOT NULL,
                                         category_id integer NOT NULL,
                                         name text NOT NULL
);


ALTER TABLE public.ms_subcategories OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16511)
-- Name: ms_subcategories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_subcategories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_subcategories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16484)
-- Name: ms_transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_transactions (
                                        id integer NOT NULL,
                                        month_id integer NOT NULL,
                                        category_id integer,
                                        subcategory_id integer,
                                        description text,
                                        datetime timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                        amount numeric(19,2) DEFAULT 0.00 NOT NULL
);


ALTER TABLE public.ms_transactions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16510)
-- Name: ms_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16405)
-- Name: ms_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_users (
                                 id integer NOT NULL,
                                 username text CONSTRAINT ms_users_user_id_not_null NOT NULL,
                                 emails text NOT NULL,
                                 first_name text,
                                 last_name text,
                                 phone_number text,
                                 password_hash text DEFAULT 'dev'::text,
                                 created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 updated_at timestamp without time zone
);


ALTER TABLE public.ms_users OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16417)
-- Name: ms_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4847 (class 2606 OID 16464)
-- Name: ms_budgets ms_budgets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_budgets
    ADD CONSTRAINT ms_budgets_pkey PRIMARY KEY (id);


--
-- TOC entry 4843 (class 2606 OID 16433)
-- Name: ms_categories ms_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_categories
    ADD CONSTRAINT ms_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4849 (class 2606 OID 16478)
-- Name: ms_months ms_months_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_months
    ADD CONSTRAINT ms_months_pkey PRIMARY KEY (id);


--
-- TOC entry 4845 (class 2606 OID 16449)
-- Name: ms_subcategories ms_subcategories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_subcategories
    ADD CONSTRAINT ms_subcategories_pkey PRIMARY KEY (id);


--
-- TOC entry 4851 (class 2606 OID 16493)
-- Name: ms_transactions ms_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_transactions
    ADD CONSTRAINT ms_transactions_pkey PRIMARY KEY (id);


--
-- TOC entry 4839 (class 2606 OID 16419)
-- Name: ms_users ms_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_users
    ADD CONSTRAINT ms_users_pkey PRIMARY KEY (id);


--
-- TOC entry 4841 (class 2606 OID 16421)
-- Name: ms_users ms_users_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_users
    ADD CONSTRAINT ms_users_user_id_key UNIQUE (username);


--
-- TOC entry 4854 (class 2606 OID 16465)
-- Name: ms_budgets ms_budgets_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_budgets
    ADD CONSTRAINT ms_budgets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.ms_users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4852 (class 2606 OID 16434)
-- Name: ms_categories ms_categories_users_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_categories
    ADD CONSTRAINT ms_categories_users_fkey FOREIGN KEY (user_id) REFERENCES public.ms_users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4855 (class 2606 OID 16479)
-- Name: ms_months ms_months_budget_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_months
    ADD CONSTRAINT ms_months_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.ms_budgets(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4853 (class 2606 OID 16450)
-- Name: ms_subcategories ms_subcategories_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_subcategories
    ADD CONSTRAINT ms_subcategories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.ms_categories(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 4856 (class 2606 OID 16499)
-- Name: ms_transactions ms_transactions_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_transactions
    ADD CONSTRAINT ms_transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.ms_categories(id);


--
-- TOC entry 4857 (class 2606 OID 16494)
-- Name: ms_transactions ms_transactions_month_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_transactions
    ADD CONSTRAINT ms_transactions_month_id_fkey FOREIGN KEY (month_id) REFERENCES public.ms_months(id);


--
-- TOC entry 4858 (class 2606 OID 16504)
-- Name: ms_transactions ms_transactions_subcategory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_transactions
    ADD CONSTRAINT ms_transactions_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES public.ms_subcategories(id);


-- Completed on 2026-06-17 15:20:57

--
-- PostgreSQL database dump complete
--

\unrestrict 7dfoNOZq59VJPcxAmaTq89l5GUvSkRMkrUCb8CsxdqMuYcXTzaLWYVkhajNKPAK

