--
-- PostgreSQL database dump
--

\restrict IYsYQfcd3dy2ozXSKUbOvLhnOYDUu6stt6frHmZxlKJ2SAOlW7lhZm7rsrWPaDn

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

-- Started on 2026-06-23 16:24:31

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16626)
-- Name: ms_budgets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_budgets (
                                   id integer NOT NULL,
                                   user_id integer NOT NULL,
                                   name text NOT NULL,
                                   is_active boolean DEFAULT false CONSTRAINT "ms_budgets_isActive_not_null" NOT NULL
);


ALTER TABLE public.ms_budgets OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16636)
-- Name: ms_budgets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_budgets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_budgets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16637)
-- Name: ms_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_categories (
                                      id integer CONSTRAINT ms_categories_category_id_not_null NOT NULL,
                                      user_id integer NOT NULL,
                                      name text CONSTRAINT ms_categories_category_name_not_null NOT NULL,
                                      description text
);


ALTER TABLE public.ms_categories OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16645)
-- Name: ms_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16646)
-- Name: ms_months; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_months (
                                  id integer NOT NULL,
                                  budget_id integer NOT NULL,
                                  year integer NOT NULL,
                                  month integer NOT NULL
);


ALTER TABLE public.ms_months OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16653)
-- Name: ms_months_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_months ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_months_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16654)
-- Name: ms_subcategories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_subcategories (
                                         id integer NOT NULL,
                                         category_id integer NOT NULL,
                                         name text NOT NULL,
                                         description text
);


ALTER TABLE public.ms_subcategories OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16662)
-- Name: ms_subcategories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_subcategories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_subcategories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16663)
-- Name: ms_transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_transactions (
                                        id integer NOT NULL,
                                        month_id integer NOT NULL,
                                        category_id integer,
                                        subcategory_id integer,
                                        description text,
                                        "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT ms_transactions_datetime_not_null NOT NULL,
                                        amount numeric(19,2) DEFAULT 0.00 NOT NULL
);


ALTER TABLE public.ms_transactions OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16674)
-- Name: ms_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16675)
-- Name: ms_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_users (
                                 id integer NOT NULL,
                                 username text CONSTRAINT ms_users_user_id_not_null NOT NULL,
                                 emails text NOT NULL,
                                 first_name text,
                                 last_name text,
                                 phone_number text,
                                 password_hash text DEFAULT 'dev'::text,
                                 created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 updated_at timestamp without time zone
);


ALTER TABLE public.ms_users OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16686)
-- Name: ms_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4840 (class 2606 OID 16688)
-- Name: ms_budgets ms_budgets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_budgets
    ADD CONSTRAINT ms_budgets_pkey PRIMARY KEY (id);


--
-- TOC entry 4842 (class 2606 OID 16690)
-- Name: ms_categories ms_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_categories
    ADD CONSTRAINT ms_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4844 (class 2606 OID 16692)
-- Name: ms_months ms_months_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_months
    ADD CONSTRAINT ms_months_pkey PRIMARY KEY (id);


--
-- TOC entry 4846 (class 2606 OID 16694)
-- Name: ms_subcategories ms_subcategories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_subcategories
    ADD CONSTRAINT ms_subcategories_pkey PRIMARY KEY (id);


--
-- TOC entry 4848 (class 2606 OID 16696)
-- Name: ms_transactions ms_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_transactions
    ADD CONSTRAINT ms_transactions_pkey PRIMARY KEY (id);


--
-- TOC entry 4850 (class 2606 OID 16698)
-- Name: ms_users ms_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_users
    ADD CONSTRAINT ms_users_pkey PRIMARY KEY (id);


--
-- TOC entry 4852 (class 2606 OID 16700)
-- Name: ms_users ms_users_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_users
    ADD CONSTRAINT ms_users_user_id_key UNIQUE (username);


--
-- TOC entry 4853 (class 2606 OID 16701)
-- Name: ms_budgets ms_budgets_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_budgets
    ADD CONSTRAINT ms_budgets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.ms_users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4854 (class 2606 OID 16706)
-- Name: ms_categories ms_categories_users_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_categories
    ADD CONSTRAINT ms_categories_users_fkey FOREIGN KEY (user_id) REFERENCES public.ms_users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4855 (class 2606 OID 16711)
-- Name: ms_months ms_months_budget_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_months
    ADD CONSTRAINT ms_months_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.ms_budgets(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4856 (class 2606 OID 16736)
-- Name: ms_subcategories ms_subcategories_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_subcategories
    ADD CONSTRAINT ms_subcategories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.ms_categories(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4857 (class 2606 OID 16741)
-- Name: ms_transactions ms_transactions_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_transactions
    ADD CONSTRAINT ms_transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.ms_categories(id) ON UPDATE SET NULL ON DELETE SET NULL NOT VALID;


--
-- TOC entry 4858 (class 2606 OID 16756)
-- Name: ms_transactions ms_transactions_month_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_transactions
    ADD CONSTRAINT ms_transactions_month_id_fkey FOREIGN KEY (month_id) REFERENCES public.ms_months(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4859 (class 2606 OID 16746)
-- Name: ms_transactions ms_transactions_subcategory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_transactions
    ADD CONSTRAINT ms_transactions_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES public.ms_subcategories(id) ON UPDATE SET NULL ON DELETE SET NULL NOT VALID;


-- Completed on 2026-06-23 16:24:31

--
-- PostgreSQL database dump complete
--

\unrestrict IYsYQfcd3dy2ozXSKUbOvLhnOYDUu6stt6frHmZxlKJ2SAOlW7lhZm7rsrWPaDn

